### ISSUE TITLE
Offset or Pager Parameter to get additional results? 

### ISSUE THREAD

**Issue by markwk** [mdorn/pyinstapaper#6]
Hi, first thanks for creating this super helpful library. Saved me a bunch of time and steps in writing some [code to get my instapaper data and do some data analysis](https://github.com/markwk/qs_ledger/blob/master/instapaper/instapaper_downloader.ipynb). 

One thing I got stuck with (and this may not be related to your code and might just be the API thing) was how to do an offset or pager? 

Basically I could get up to 500 bookmarks but beyond that I wasn't sure what to do. Might be missing something stupid and any help would be much appreciated. 

Thanks again for creating and sharing this instapaper integration code!

**Comment by mdorn** [comment]
Hi @markwk -- this appears to be a limitation of the Instapaper API. If you look at the documentation [here](https://www.instapaper.com/api/full) under "Bookmark methods" you won't find any mention of paging.  One thing you might try is to add all 500 of the bookmarks that you can get to the `have` parameter when getting bookmarks to see if it will exclude those and send you the next batch of available items, e.g.:

    bookmarks = instapaper.get_bookmarks('unread', have=['id1', 'id2', ... 'id500'])

Not sure if you'll run into some sort of API input limitation by trying that though.

Good luck!

**Comment by markwk** [comment]
Thanks @mdorn Really great tip. Unfortunately, no luck. That method does remove items you already have but it doesn't pull anything farther in the past than the 500 item limit. So you can avoid re-pulling what you already have but nothing more. 

I've posted a request to the Instapaper team and got a response saying that following:

> Thanks for writing in. Sorry for any inconvenience, that is the current limit. The API was built more to accommodate continuous processes tied to Instapaper rather than retroactive ones for all account items. We'll keep expanding that in mind when we do future API work.
> 
> Let me know if there's anything else I can do for you for now. Thanks again for the feedback and for using Instapaper.

My expectations are low that they'll make a change based on their initial response so one could get the historical data. Out of curiosity: Have you had any past interactions with Instapaper team? Gotten any API bug fixes or changes made?

**Comment by mdorn** [comment]
@markwk Yes, it sounds like no changes will be forthcoming.  I recall having some interactions with someone about the API and getting quick responses, but nothing regarding getting anything changed.

For your purposes I guess you'd have to build your own scheduled task to continuously update your own database to maintain bookmark history.

**Comment by markwk** [comment]
That’s true but I already got 5000+ bookmarks archived that I’d still like
to get :)
